esphome:
  name: $device_name
  platform: ESP8266
  board: $board_model
  build_path: build/$device_name
  esp8266_restore_from_flash: yes


substitutions:
  board_model: nodemcuv2
  device_name: ir_blaster
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_fast_connect: 'true'
  wifi_reboot_timeout: 600s
  ota_password: !secret ota_password
  api_reboot_timeout: 600s


wifi:
  ssid: $wifi_ssid
  password: $wifi_password
#  manual_ip:
#    static_ip: 192.168.178.230
#    gateway: 192.168.178.1
#    subnet: 255.255.255.0
#    dns1: 1.1.1.1
#    dns2: 1.2.2.1
#----------------------------------------------------
  domain: .local
  reboot_timeout: $wifi_reboot_timeout
  power_save_mode: none
  fast_connect: $wifi_fast_connect
  ap:
    ssid: $device_name
    password: $wifi_password
    ap_timeout: 30s

captive_portal:

#--------------------------------------------
web_server:
 port: 80
 css_url: https://esphome.io/_static/webserver-v1.min.css
 js_url: https://esphome.io/_static/webserver-v1.min.js
#----------------------------------------------------


# Enable logging
logger:
  hardware_uart: UART0
  level: DEBUG
  baud_rate: 115200

status_led:
  pin: 
    number: GPIO2
    inverted: True

api:
  password: $ota_password

ota:
  password: $ota_password


remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

climate:
  - platform: coolix
    name: "Kelong AC"


switch:
  - platform: template
    name: Raw Code Power Button
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [4088, -1542, 1019, -510, 513, -1019, 510, -509, 511, -510, 1020,
                 -1020, 1022, -1019, 510, -509, 511, -510, 511, -509, 511, -510,
                 1020, -1019, 510, -511, 1020, -510, 512, -508, 510, -1020, 1022]